"""history

Revision ID: 27887efeb8b9
Revises: 991e72d76ea2
Create Date: 2025-09-10 21:39:51.222358

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27887efeb8b9'
down_revision: Union[str, Sequence[str], None] = '991e72d76ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('upload_image', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_data', sqlmodel.sql.sqltypes.AutoString(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_task_id'), 'history', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_task_id'), table_name='history')
    op.drop_table('history')
    # ### end Alembic commands ###
