"""add score

Revision ID: 991e72d76ea2
Revises: 8752b84f54c4
Create Date: 2025-09-05 15:11:35.112466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '991e72d76ea2'
down_revision: Union[str, Sequence[str], None] = '8752b84f54c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usertable', sa.Column('score', sa.Integer(), server_default='30', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usertable', 'score')
    # ### end Alembic commands ###
