"""Add job_id and status to history table

Revision ID: a1dff0972af0
Revises: 27887efeb8b9
Create Date: 2025-09-10 22:08:11.164454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a1dff0972af0'
down_revision: Union[str, Sequence[str], None] = '27887efeb8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True))
    op.execute('UPDATE history SET job_id = gen_random_uuid() WHERE job_id IS NULL')
    op.alter_column('history', 'job_id', nullable=False)

    op.alter_column('history', 'status',
               existing_type=sa.BOOLEAN(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=False,
               server_default='PENDING')
    op.execute('UPDATE history SET status = \'COMPLETED\' WHERE status IS NULL')

    op.alter_column('history', 'task_id',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.create_index(op.f('ix_history_job_id'), 'history', ['job_id'], unique=True)
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_job_id'), table_name='history')
    op.alter_column('history', 'task_id',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('history', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    op.drop_column('history', 'job_id')
    # ### end Alembic commands ###
